# Site settings
title: PureBeauty
email: stefan.yohansson@agnesit.tech
description: "minimalistic, sexy, beautiful (jekyll) theme."
baseurl: ""
url: ""
github_username:  StefanYohansson

# Build settings
markdown: kramdown
permalink: pretty
