# Site settings
title: SnotrLog
email: stefan.yohansson@agnesit.tech
description: "Stefan' (aka snotr) personal blog"
baseurl: ""
url: ""
github_username:  StefanYohansson

# Build settings
markdown: kramdown
permalink: pretty
